### ISSUE TITLE
Formatting issue for MPU-6050

### ISSUE THREAD

**Issue by CWempe** [tasmota/docs#1054]
There seems to be a formatting issue for the documentation of [MPU-6050](https://tasmota.github.io/docs/MPU-6050/).

![image](https://user-images.githubusercontent.com/1270359/192108505-63efbf69-5b1d-4adc-b23d-d7ef54c940bc.png)

I guess it should look similar to this:

![image](https://user-images.githubusercontent.com/1270359/192108487-d787bd25-3eec-4731-bf47-2b3d5172439a.png)

I know markdown, but I cannot see an obvious error.
So maybe someone else can fix this .

I suspect the indentation is wrong.

![image](https://user-images.githubusercontent.com/1270359/192108594-db5b4e0e-16b7-4e0a-b0e5-8f2aec621a52.png)

**Comment by blakadder** [comment]
fixed
