### ISSUE TITLE
Please provide List of JSON [{'command':'Description'}] for tasmota Opentherm

### ISSUE THREAD

**Issue by constcr** [tasmota/docs#1129]
@
re PR: arendst/tasmota#

Please add the new feature to the appropriate article in [Tasmota documentation](https://github.com/tasmota/docs)
I need to change the BTMP value, and i am unable to find what it means. Could you please add a description for all the fields?

{"sn":{"Time":"2022-12-13T18:40:13","OPENTHERM":{"conn":"READY","settings":6,"SLAVE":{"FAULT":0,"CH":1,"DHW":0,"FL":0,"COOL":0,"CH2":0,"DIAG":0,"RAW":1073741826},"BTMP":{"FAULT":0,"REQ":25.0,"ACT": 25.0},"HWTMP":{"REQ":36.0,"ACT": 36.0},"ASFF":{"FC":0,"OFC":0},"OEMD":0,"FLM":0.0,"TB":25.0,"TDHW":41.8,"TRET":26.3,"DHWS":36.0,"TMAX":45.2,"OT10":{"lo":0,"hi":0},"OT12":{"lo":0,"hi":0},"OT14":0.0,"OT15":{"lo":17,"hi":0},"OT18":1.7,"OT19":0.0,"OT33":31}},"ver":1}

**Comment by barbudor** [comment]
How could you know that you have to change it and don't know what it means ?

Whatever, this is OpenTherm specific. Like Tamsota doc is not going to explain how HTTP or MQTT works, please refer to OpenTherm documentation for the details.
