### ISSUE TITLE
Correct LOGAREX Config 

### ISSUE THREAD

**Issue by RFM69CW** [tasmota/docs#1240]
@
re PR: arendst/tasmota#

Please add the new feature to the appropriate article in [Tasmota documentation](https://github.com/tasmota/docs)

LOGAREX LK13BE803039 does send the data by itself and it causes wrong readings when tx is configured.

example config:
`
>D
>B
=>sensor53 r
>M 1
+1,3,o,16,9600,LK13BE

1,1-0:1.8.0*255(@1,Gesamtverbrauch,KWh,total,4
1,1-0:1.8.0*96(@1,Verbrauch 1 Tag,KWh,total_1d,4
1,1-0:1.8.0*97(@1,Verbrauch 7 Tage,KWh,total_7d,4
1,1-0:1.8.0*98(@1,Verbrauch 30 Tage,KWh,total_30d,4
1,1-0:1.8.0*99(@1,Verbrauch 365 Tage,KWh,total_365d,4
1,1-0:16.7.0*255(@1,Verbrauch aktuell,W,current,20
1,1-0:2.8.0*255(@1,Gesamteinspeisung,KWh,total_out,4
#

`

**Comment by blakadder** [comment]
the edit button is in the top right corner
