### ISSUE TITLE
Possible wrong description in TouchPin.md

### ISSUE THREAD

**Issue by CWempe** [tasmota/docs#1271]
There seems to be a wrong description in https://github.com/tasmota/docs/blob/master/docs/TouchPin.md?plain=1#L22.

Both the first and the second command are described as:

> This plots the sensor values to the console, to get information regarding the setting of the 2 following commands

I guess `TouchThres` is for something like "Set the Threshold at wich the sensor should interpret the value as a button press".

But I am not sure as it is the first time I want to use this feature.

**Comment by CWempe** [comment]
According to https://github.com/tasmota/docs/commit/ffbf5438ad37bead23f9ecf33c5244a7ee662762, the correct description might be:

> sets threshold to x, which will get smaller by touching the pin. In the driver a sensor value beneath that threshold, will trigger a button touch.

@Staars 
Can you say anything about this?

**Comment by Staars** [comment]
It’s been awhile that I played with the touch pins.
Yes, this looks like a copy-paste-error, but I am not sure, if my initial implementation was altered later on.
You can simply test the calibration process on the console. The initial idea was indeed to set the threshold value with `TouchThres` for a touch button.
I must take a look at the code, if things have changed …

**Comment by Staars** [comment]
… and indeed, `TouchNum` was removed.
I guess, that Theo did some testings and found, that sensing the value of the touch pins over multiple loops, did not justify the resulting lag for benefit of filtering out spikes. It is possibly, that these sensing errors are less frequent with the newer SDK, than I did see when I did my initial testing.
Anyway, this command is gone and the touch button is a bit faster now, although measuring is technically not super quick.

**Comment by CWempe** [comment]
Thanks for clarifying.

Do you intend to edit the page?
Or should I create a PR to remove the command from the docs?

**Comment by Staars** [comment]
I am sorry that it took so long. Should be correct now.

**Comment by CWempe** [comment]
Great. Thanks.

Just for protocol.
It is this Commit:  https://github.com/tasmota/docs/commit/117d6ddd87cfa747b39b543b04581e8d34bd4811
