### ISSUE TITLE
Please update the documentation for the LC Technology WiFi Relay - Quad Relay

### ISSUE THREAD

**Issue by greytdepression** [tasmota/docs#1407]
I have just set up the [LC Tech Quad Relay](https://github.com/tasmota/docs/blob/master/docs/devices/LC-Technology-WiFi-Relay.md) and it seems mine also uses the Nuvoton N76E003AT20 chip. I thus had to send the same serial commands as in the Relay X2 section and break up the rule into two rules for the data to fit.
I also had to press switch S1 instead of S2 to get back to mode 1.

I'm new to tasmota, so figuring all of this out took me a while and I'd like to append this info to the documentation to make it easier for others to figure out in the future. I'd be happy to open up a PR with those changes if I get the go ahead!

**Comment by barbudor** [comment]
There's never a blocking to propose a PR on the docs
All contributions are welcome
You may get comments is someone suggest a rewording or changes to match doc style

Go go go
