### ISSUE TITLE
Please, add docs for I2C HT16K33 based 7 segment LED

### ISSUE THREAD

**Issue by blakadder** [tasmota/docs#257]
@tthk
re: arendst/Tasmota/pull/8116

**Comment by barbudor** [comment]
Not sure what is expected here.
Would it be better that the code author @tthk write something ?

**Comment by blakadder** [comment]
that is exactly what is expected :D

**Comment by tamoghna-dey** [comment]
What is this issue about?

**Comment by ascillato** [comment]
Originally posted by HarHarLinks at https://github.com/tasmota/docs/issues/902 :
----

@tthk
PRs like arendst/tasmota#8116, arendst/tasmota#8900 seem to not have made it to the docs properly.

For a list of things I couldn't find in the docs, see https://github.com/arendst/Tasmota/discussions/14451

Please add the new feature to the appropriate article in [Tasmota documentation](https://github.com/tasmota/docs)

**Comment by HarHarLinks** [comment]
Hello @blakadder, can you please provide a link to where this missing documentation was added? I can not find any recently added info about the "DisplayMode 11" generic common anode 7 segment display mode driver, i.e. this issue is not resolved.

**Comment by blakadder** [comment]
noone said it was resolved, its closed since noone cares

**Comment by HarHarLinks** [comment]
Sounds like a great way to handle things :+1:

> blakadder closed this as completed

You could at least have closed it as wontfix then.

**Comment by blakadder** [comment]
You're more than welcome to contribute the actual content instead of complaining.

**Comment by markfickett** [comment]
Not full docs, but [here's a discussion](https://github.com/arendst/Tasmota/discussions/20202) where I got help using HT16K33 I2C seven segment displays. (I'm working on a [PR for docs](https://github.com/tasmota/docs/pull/1312) for another peripheral and if that process isn't too hard, glad to come back and boil the discussion down to a docs page too.)
