### ISSUE TITLE
Please add the new feature to documentation

### ISSUE THREAD

**Issue by DelroyTaylor** [tasmota/docs#273]
@
re PR: arendst/tasmota#

Please add the new feature to the appropriate article in [Tasmota documentation](https://github.com/tasmota/docs)

Please fully explain how to use I2CWRITE and I2CREAD at the console to debug I2C devices.
What is the correct syntax for I2CWrite?
Please explain "I2C: Result 0", "I2C: Result 2" etc..

Example. 1.
If I enter  **i2cwrite 70, 1** in the console I receive **I2C: Result 0**:  
70 is the I2C address
1 is the data

04:53:13 CMD: i2cwrite 70, 1
04:53:13 CMD: Group 0, Index 1, Command "I2CWRITE", Data "70, 1"
04:53:13 DMP: 70 01
04:53:13 I2C: Result 0
04:53:13 MQT: stat/PoolControl_08EBDC/RESULT = {"I2CWrite":"Done"}

Example 2.
If I enter  **i2cwrite (70, 1)** in the console I receive **I2C: Result 2**: 
70 is the I2C address
1 is the data

04:58:29 CMD: i2cwrite (70, 1)
04:58:29 SRC: WebConsole from 192.168.0.27
04:58:29 CMD: Group 0, Index 1, Command "I2CWRITE", Data "(70, 1)"
04:58:29 DMP: 00 01
04:58:29 I2C: Result 2
04:58:29 MQT: stat/PoolControl_08EBDC/RESULT = {"I2CWrite":"Done"}

Thank You

**Comment by blakadder** [comment]
Those are developer only options and noone offered to document them yet. You can be the One!

**Comment by DelroyTaylor** [comment]
I would like to document them but I don't understand them. That is why I
made the request. If you could explain what you know about the commands and
how they work I could document them.

Sincerely

**Comment by curzon01** [comment]
These commands are documented within the debug driver source [xdrv_99_debug.ino](https://github.com/arendst/Tasmota/blob/development/tasmota/xdrv_99_debug.ino) 

CmndI2cWrite()
`I2cWrite <address>,<data>...`

CmndI2cRead()
`I2cRead <address>,<size>`

There are few other debug commands in this debug driver (see `Debug commands` at the beginning). Read the Tasmota source.

**Comment by DelroyTaylor** [comment]
I understand the syntax of the commands but I don't understand the response
from 8266/esp32.
Eg. What response is expected after issuing command for errors, success
etc...?

**Comment by curzon01** [comment]
I'm just wondering why you do not read the module source or simply try it:

`I2CRead` response with the data read `DMP: xx xx xx xx xx...` and `I2cWrite` response with `I2C: Result d` where `xx` are the hex binary data received and `d` is the decimal return value of the I2C library call Wire.endTransmission()

The results themselves depend on the I2C device to be examined, so you have to consult the I2C manufacturer's data sheets
