### ISSUE TITLE
Please add the new feature to documentation

### ISSUE THREAD

**Issue by EddieMIT** [tasmota/docs#280]
@
re PR: arendst/tasmota#

Please add a note to the documentation in Flash-Sonoff-using-Raspberry-Pi.md (https://github.com/tasmota/docs/blob/master/docs/Flash-Sonoff-using-Raspberry-Pi.md)

Step 1 installs esptool with PIP. The note should say it may be necessary to install the esptool from source. While trying to erase_flash on a Sonoff S31, I got a message saying function was not supported (sorry, I did not save the error message).

**Comment by blakadder** [comment]
Please read https://tasmota.github.io/docs/Contributing/ on how to edit an article
