### ISSUE TITLE
Dead Links on tasmota.github.io

### ISSUE THREAD

**Issue by JeffResc** [tasmota/docs#311]
I've collected a list of dead URLs found on templates.blakadder.com in [this Google Sheet](https://docs.google.com/spreadsheets/d/19zwdyQzE8dnqTD2cLVd8nnsBuvmw9cYWqjmu9JUsAVE/edit?usp=sharing). These URLs are mostly composed of pages with 404 links that should be updated to where the webpage was moved.

**Comment by Jason2866** [comment]
Thx, but without the source where the dead links are it is useless
