### ISSUE TITLE
Upgrading and Power Calibration

### ISSUE THREAD

**Issue by andre68723** [tasmota/docs#314]
Hello,

could you add a notice on the behavior of Power Calibration when upgrading?
I search the main repo and the docs but could not find specific information about it

In my case that would be 8.2->8.3 and the devices are now built-in, hence I was looking
for information beforehand

Thanks, Andre

**Comment by blakadder** [comment]
What kind of notice on upgrading? Have you read the Upgrading article

**Comment by andre68723** [comment]
Yes, I read https://github.com/tasmota/docs/blob/master/docs/Upgrading.md
to my understanding, 8.2 + 8.3 use the same parameter storage. 

Does that imply that also any PowerSet, VoltageSet + CurrentSet would be retained?

**Comment by ascillato** [comment]
While upgrading, all parameters are retained because they are stored outside the program range.
