### ISSUE TITLE
Please add the new feature to documentation

### ISSUE THREAD

**Issue by MubiTec** [tasmota/docs#371]
@
re PR: arendst/tasmota#

Please add the new feature to the appropriate article in [Tasmota documentation](https://github.com/tasmota/docs)

Hi, 
I had an issue using the mpr121 at a wemos d1 mini. According to described wiring it connected sda and scl to d2 and d1 of the wemos, but it didn't work. 
So I tried to connect them to rx and tx of the wemos and it works. Perhaps you can document this fact as an alternative wiring for wemos in the documentation.

**Comment by blakadder** [comment]
you can connect and define scl and sda to almost any gpio, the guide doesn't specify to use d1 and d1. the ones selected in the screenshot are just an example. it is also not recommended to use tx and rx pins for different purposes if you don't know what exactly you're doing
