### ISSUE TITLE
Add support for LC Technology v3 - Single Relay

### ISSUE THREAD

**Issue by greg-love** [tasmota/docs#375]
@
re PR: arendst/tasmota#

Please edit [Commands.md](https://github.com/tasmota/docs/blob/master/docs/Commands.md) and include new additions.

Please can you add support for v3 of the LC Tech Relays
![IMG_3352](https://user-images.githubusercontent.com/67560217/85957732-26774000-b990-11ea-9ae9-aba49bf06937.jpg)
![IMG_3351](https://user-images.githubusercontent.com/67560217/85957733-29723080-b990-11ea-86d6-75dda9f7de93.jpg)

**Comment by blakadder** [comment]
https://templates.blakadder.com
