### ISSUE TITLE
Please amend Shelly1 documentation page

### ISSUE THREAD

**Issue by gdelconti** [tasmota/docs#395]
Wrong image,  GPIO5 reads **HIGH** when SW is shorted to AC/L. Here below the updated image:

![ScreenShot005](https://user-images.githubusercontent.com/12270306/88280734-a15d1d80-cce6-11ea-99c1-5fa9790b0f92.png)
@
re PR: arendst/tasmota#

Please amend the appropriate article in [Tasmota documentation](https://github.com/tasmota/docs)

**Comment by blakadder** [comment]
done
