### ISSUE TITLE
I'd like to add a note about the Sonoff Slampher to the docs, but need a pointer

### ISSUE THREAD

**Issue by hartzell** [tasmota/docs#403]
I just received a Sonoff Slampher and tried following the various Internet instructions that suggest grounding the CPU side of R9 to get it into programming mode.  R9 is no longer present in the location that the tutorials suggest.  I checked which pin it uses on the CPU package and believe that it's on a trace that either goes nowhere or through a via to the other side of the board.

I was about to give up when I discovered that, contrary to the various instructions, simply holding down the button while connecting the vcc/tx/dx/gnd pins put it into programming.  It flashed on the first try.

I'd like to leave a note somewhere, but can't find any Sonoff hardware pages.

Is there an appropriate location?

Thanks.

**Comment by meingraham** [comment]
You can visit this link - https://tasmota.github.io/docs/devices/Sonoff-Slampher/

In the upper right is a "pencil" that allows you to visit the source page to edit the note by clicking the "pencil" (again). There add your note and submit the requested change to the documentation.

**Comment by hartzell** [comment]
Done.  Thanks!
