### ISSUE TITLE
Please add the new feature to documentation - Max value rule

### ISSUE THREAD

**Issue by pippin88** [tasmota/docs#447]
@
re PR: arendst/tasmota#

Please add the new feature to the appropriate article in [Tasmota documentation](https://github.com/tasmota/docs)

Can documentation about analog be improved? I could not find anywhere the list of value names. All rule examples use analog#a0, which did nothing for me, perhaps because I'm using ESP32? I worked out that analog#a1 got a value and then eventually, by trial and error I worked out I could use analog#range1.

I would like to suggest the following example for the rules cookbook:

**Publish Maximum Value from sensor in a time period:**
This rule stores the sensor value in VAR1. When the current value is greater than the previous, VAR1 is updated. If the current value is smaller, VAR1 is unchanged. Then every minute, VAR1 is published and then VAR1 is reset.
This results in output of the maximum/peak value for the minute. Useful, for example in a decibel meter, when the peak value is important, rather than the value that is occurring by chance at normal telemetry time.
This uses Analog range (analog#range1) which is a scaled output value. The raw analog value is analog#a1

Rule
ON System#Boot var1 1 ENDON
ON analog#range1>%var1% DO VAR1 %value% ENDON
ON Time#Minute DO Backlog publish shed/tele/maxdb %var1%; var1 1 ENDON

**Comment by barbudor** [comment]
https://github.com/tasmota/docs/commit/c2d858506dd0f00374468b4fbb8004cd332a52fd
