### ISSUE TITLE
WIFI - CORS : Error in commands page or a bug

### ISSUE THREAD

**Issue by JanKerstens** [tasmota/docs#475]
the current version for WIFI - CORS states 

                               " = disable CORS (Cross Origin Resource Sharing) (default)

but when checking with OWASP ZAP, it seems as if the _* = enable_ value is the default.

I am not capable to dive into the code to see if it is a bug or if it is a doc issue.
If you direct me to a bug page, I can post there if required.

**Comment by ascillato** [comment]
CORS is disabled by default. You need to set the website is going to use CORS into your device.
