### ISSUE TITLE
Tasmota not working with ant mqtt cloud broker

### ISSUE THREAD

**Issue by arj44ac** [tasmota/docs#488]
I tried to make it work with dozens of mqtt cloud broker but no results. Can u pls post an example(tested) with the most common brokers? Cloudmqtt, hive, thingspeak,...it would be great to have more documentation.thanks

**Comment by blakadder** [comment]
documentation required to connect to a broker is up to the brokers development team, settings in tasmota are identical whether you use a local or "cloud" broker
