### ISSUE TITLE
mqtt - Securing your IoT from hacking

### ISSUE THREAD

**Issue by panache67** [tasmota/docs#5]
The suggested access control rules break the Home Assistant MQTT (auto) discovery functionality as  the tasmota device tries to write to a number of homeassistant/# topics. 
Is there a clever way to fix it for all tasmota devices?

**Comment by effelle** [comment]
I'm not sure If I understood what you mean. Care to share more details?

Thanks.

F.

Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by panache67** [comment]
The proposed configuration for securing Mosquitto suggests to allow each Tasmota device, i.e. mqtt user account, to only write to the stat and tele topics and read from the cmnd topic.
```
pattern read cmnd/%u/# 
pattern write stat/%u/# 
pattern write tele/%u/# 
```
If one wants to use the Home Assistant mqtt autodiscovery function to control Tasmota device and activates that by executing ```SetOption19 1```, the Tasmoto device tries to write mqtt messages to a number of homeassistant topics to advertise the device e.g. 

```
20:00:50 CMD: SetOption19 1
20:00:50 MQT: sonoff-0280/stat/RESULT = {"SetOption19":"ON"}
20:00:51 MQT: homeassistant/light/D1A118_LI_1/config =  (retained)
20:00:51 MQT: homeassistant/switch/D1A118_RL_1/config = {"name":"Sonoff","cmd_t":"~cmnd/POWER","stat_t":"~tele/STATE","val_tpl":"{{value_json.POWER}}","pl_off":"OFF","pl_on":"ON","avty_t":"~tele/LWT","pl_avail":"Online","pl_not_avail":"Offline","uniq_id":"D1A118_RL_1","device":{"identifiers":["D1A118"],"connections":[["mac","XX:XX:XX:XX:XX:XX"]]},"~":"sonoff-0280/"} (retained)
20:00:51 MQT: homeassistant/light/D1A118_LI_2/config =  (retained)
20:00:51 MQT: homeassistant/switch/D1A118_RL_2/config =  (retained)
20:00:51 MQT: homeassistant/light/D1A118_LI_3/config =  (retained)
20:00:51 MQT: homeassistant/switch/D1A118_RL_3/config =  (retained)
20:00:51 MQT: homeassistant/light/D1A118_LI_4/config =  (retained)
20:00:51 MQT: homeassistant/switch/D1A118_RL_4/config =  (retained)
20:00:51 MQT: homeassistant/light/D1A118_LI_5/config =  (retained)
20:00:51 MQT: homeassistant/switch/D1A118_RL_5/config =  (retained)
20:00:51 MQT: homeassistant/light/D1A118_LI_6/config =  (retained)
20:00:51 MQT: homeassistant/switch/D1A118_RL_6/config =  (retained)
20:00:51 MQT: homeassistant/light/D1A118_LI_7/config =  (retained)
20:00:51 MQT: homeassistant/switch/D1A118_RL_7/config =  (retained)
20:00:51 MQT: homeassistant/light/D1A118_LI_8/config =  (retained)
20:00:51 MQT: homeassistant/switch/D1A118_RL_8/config =  (retained)
20:00:51 MQT: homeassistant/binary_sensor/D1A118_BTN_1/config = {"name":"Sonoff Button1","stat_t":"~stat/RESULT","value_template":"{{value_json.BUTTON1}}","pl_on":"TOGGLE","avty_t":"~tele/LWT","pl_avail":"Online","pl_not_avail":"Offline","uniq_id":"D1A118_BTN_1","device":{"identifiers":["D1A118"],"connections":[["mac","XX:XX:XX:XX:XX:XX"]]},"~":"sonoff-0280/","off_delay":1} (retained)
20:00:51 MQT: homeassistant/binary_sensor/D1A118_BTN_2/config =  (retained)
20:00:51 MQT: homeassistant/binary_sensor/D1A118_BTN_3/config =  (retained)
20:00:51 MQT: homeassistant/binary_sensor/D1A118_BTN_4/config =  (retained)
20:00:51 MQT: homeassistant/binary_sensor/D1A118_SW_1/config =  (retained)
20:00:51 MQT: homeassistant/binary_sensor/D1A118_SW_2/config =  (retained)
20:00:51 MQT: homeassistant/binary_sensor/D1A118_SW_3/config =  (retained)
20:00:51 MQT: homeassistant/binary_sensor/D1A118_SW_4/config =  (retained)
20:00:51 MQT: homeassistant/binary_sensor/D1A118_SW_5/config =  (retained)
20:00:51 MQT: homeassistant/binary_sensor/D1A118_SW_6/config =  (retained)
20:00:51 MQT: homeassistant/binary_sensor/D1A118_SW_7/config =  (retained)
20:00:51 MQT: homeassistant/binary_sensor/D1A118_SW_8/config =  (retained)
20:00:51 MQT: homeassistant/sensor/D1A118_status/config = {"name":"Sonoff status","stat_t":"~HASS_STATE","avty_t":"~LWT","pl_avail":"Online","pl_not_avail":"Offline","json_attributes_topic":"~HASS_STATE","unit_of_meas":" ","val_tpl":"{{value_json['RSSI']}}","ic":"mdi:information-outline","uniq_id":"D1A118_status","device":{"identifiers":["D1A118"],"connections":[["mac","XX:XX:XX:XX:XX:XX"]],"name":"Sonoff","model":"AWP08L","sw_version":"6.7.1(sonoff)","manufacturer":"Tasmota"},"~":"sonoff-0280/tele/"} (retained)
```
I wonder whether there is a best practice how to allow Tasmota mqtt users to write (once?) to the different homeassistant topics using an elegant pattern?

Thank you very much for your help.

**Comment by effelle** [comment]
on OP you wrote:
> The suggested access control rules break the Home Assistant MQTT (auto) discovery functionality as the tasmota device tries to write to a number of homeassistant/# topics.

I'm trying to understand what you exactly mean here, because the integration works as expected and I don't see any issue.
A little background, just to be sure we are on the same page: 
all the topics you see are for the default configuration (excluding specific sensor like temperature, humidity and so on): eight for relay or light (RL/LI) depending by `SetOption30` status, four buttons, eight switches plus a status sensor. All the topics follow the pattern proposed by [MQTT integration](https://www.home-assistant.io/docs/mqtt/discovery/) under HA. Basically what you see is a series of reserved topics that Tasmota can use for every device and Home assistant will look on those topics under `/homeassistant` continuously. 
When a sensor/binary_sensor is not present Tasmota will send out an empty configuration (all the topics with just `retained` on list) so HA will skip quickly and pass to the following topic. That list will show up every time you reboot your device or after activating `setoption19`. 
A practical example:
You have a relay set as `Relay1`. Later you will remove it and add `Relay2` instead. 
On next reboot the integration  will see the change, then will send a empty configuration for `Relay1` and will create a new one for `relay2`.
That`s why we have so many topics created and due to our internals I don't see any other way to create the topics.

**Comment by panache67** [comment]
Apologies, I think I haven't expressed it clearly enough. 

The proposed Mosquitto access control configuration to secure one's environment only works in a non-Home Assistant environment. 
```
pattern read cmnd/%u/# 
pattern write stat/%u/# 
pattern write tele/%u/# 
```
If run in a Home Assistant environment and ```SetOption19 1``` gets activated on a Tasmoto device two things change:
1. The FullTopic pattern changes from ```%prefix%/%topic%/``` to ```%topic%/%prefix%```. 
That fact is also documented [here](https://tasmota.github.io/docs/#/integrations/Home-Assistant) 
As a result the Mosquitto access control configuration must be changed to:
```
pattern write %u/tele/#
pattern read %u/cmnd/#
```
2. To advertise itself to HA, Tasmoto writes to the previously mentioned HA topics which will be blocked as there is no pattern or user specific rules defined that allows the user to write to those topics. I don't see a clever pattern method to allow the Tasmoto user to post to the HA without having to specify a rule per user, e.g. 
```user sonoff-0280
topic write homeassistant/#```

**Comment by effelle** [comment]
@ascillato ?

**Comment by blakadder** [comment]
I fail to undestand the issue here. If someone uses Tasmota doesn't mean they use HA. The fact that Tasmota changes default %prefix%/%topic% is documented in the HA article. If you're running both this article doesn't apply. You're welcome to submit a PR with an addendum concerning HA users

**Comment by ascillato** [comment]
@effelle Sorry, I don't understand the problem. HA autodiscovery is using the method of topics and commands as required by Home Assistant, and it is working fine.

**Comment by effelle** [comment]
@ascillato is why I pinged for some help, I don't see the issue with the integration and I followed the latest directives for protocol. anyway glad there is no issue!
