### ISSUE TITLE
GPIO Conversion - Unclear consecuences/mechanisms of upgrading from 8.5.1 to 9.1

### ISSUE THREAD

**Issue by sibero80** [tasmota/docs#511]
@
re PR: arendst/tasmota#

Please add the new feature to the appropriate article in GPIO-Conversion.md or Upgrading.md (https://github.com/tasmota/docs)

It is clear in the changelog and the GPIO conversion page, that a significant change has been made.
However, it doesnt seem inmediately clear what the impact is for the end user, specially when upgrading.

It might be that I missed it, but there is no metion of this on the release notes, GPIO conversion page or Upgrade page.

Even if there ar no consecuences for the end user, at least a note of this would be good to reassure people that could be unaware of the consecuences/implications when reading the changelog.

**Comment by blakadder** [comment]
There is no impact
