### ISSUE TITLE
PZEM-004 v3 

### ISSUE THREAD

**Issue by sky7176** [tasmota/docs#512]
I loaded the firmware 9.1.0 (sensors) on a D1 MINI to be able to use it with the PZEM-004 V3
I have configured the D1 in the following way:
Tx GPIO01 -> PZEM0xx TX
Rx GPIO03 -> PZEM004 RX

But with this configuration I was not able to get any reading from PZEM004

I changed Rx GPIO03 like this: PZEM016 Rx and by doing so I was able to get readings from the device.

Why does this happen?

Thank you very much

**Comment by lustyffh** [comment]
same for me as well. Upgraded from 8.5 to 9.1 and there you are! I was tearing hairs trying to find the issue until I discovered this thread.

**Comment by blakadder** [comment]
unrelated
