### ISSUE TITLE
Upgrading Link to 6.7.1 is broken

### ISSUE THREAD

**Issue by karlkashofer** [tasmota/docs#530]
Clicking on the link for the 6.7.1 firmware in the upgrade flow line yields 404 error.

currently its pointing to:
https://github.com/arendst/Tasmota/releases/download/v6.7.1/sonoff-classic.bin
which gives 404 error

I think the correct link is:
https://github.com/arendst/Tasmota/releases/download/v6.7.1/sonoff-basic.bin

at least thats what worked for me. :)
thanks for your efforts !

**Comment by blakadder** [comment]
fixed, thanks
