### ISSUE TITLE
Buttons Default State unclear

### ISSUE THREAD

**Issue by fabian727** [tasmota/docs#581]
@
re PR: arendst/tasmota#

[buttons docs](https://tasmota.github.io/docs/Buttons-and-Switches/#button) does not state whether the 

> A push-to-make button should use a Button<x> component ...

should have default state LOW or HIGH
but should be HIGH

I would recommend rewriting (but too much effort forking ... )

`A push-to-make (default high) button should use a `Button<x>` component while a push-to-break (default low) button should use `Button<x>i` (i.e., inverted).`

**Comment by blakadder** [comment]
what does (default high) mean? how do you intend to explain that to an average user that doesn't have any electronics knowledge?

**Comment by fabian727** [comment]
Hi,
default high = VCC. There are enoguh
[buttons.zip](https://github.com/tasmota/docs/files/5791243/buttons.zip)
just drawed those four pictures with [this page](https://www.circuit-diagram.org/editor/)
You can use them to discribe default high/ low. If the reader does not understand it, he should google it.
I did google pushToBreak, which just states, that the button does break the connection if pressed. As you can see in my pictures itis not clear, which state it is in default state (unpressed) (logic '1' or '0').

**Comment by blakadder** [comment]
then they can google everything and there is no need to add the remarks you proposed

**Comment by fabian727** [comment]
There is no default state for an pushToBreak button... so you can spare your explanation in the docs. You can see that in my pictures.
