### ISSUE TITLE
Please add Sonoff Basic R2 V1.3 to documentation

### ISSUE THREAD

**Issue by RigacciOrg** [tasmota/docs#585]
I just purchased a Sonoff Basic, it is R2 V1.3, which is not covered into the page [Sonoff-Basic.md](https://github.com/tasmota/docs/blob/master/docs/devices/Sonoff-Basic.md).
I flashed it as usual using the serial. If you are interested, you can view and freely copy some photos from here: [Sonoff Basic R2 V1.3](https://www.rigacci.org/wiki/doku.php/doc/appunti/hardware/iot#sonoff_basic_r2). In the photos you view the Dupont pin headers, which I soldered on the PCB.

**Comment by blakadder** [comment]
A person who owns the device should add it.

You didn't mention what are the differences compared to v1.0
