### ISSUE TITLE
Documentation does not appear to explain how to detach switches

### ISSUE THREAD

**Issue by JeffersonRyan** [tasmota/docs#597]
I'm using Tasmota 9.2.0
 
at
https://tasmota.github.io/docs/Buttons-and-Switches/

One paragraph starts with "To detach switches" and stops there. What follows does not appear to explain how to detach the switches at all. Only waaay below, there is a section called "Detach Switches Based On.."  

The way it is written, it appears some explanation was there but got accidentally erased.

My primary language is not English, so excuse me for any mistake.

**Comment by barbudor** [comment]
"Detach Switches Based On.." is the title of the section which introduce 4 different ways of detaching switches from relay.
Can't see what we could say more.

**Comment by JeffersonRyan** [comment]
The text was fixed on a commit at the same day I opened this. 
You "Can't see what we could say more" but it seems blakadder could.

**Comment by JeffersonRyan** [comment]
You said there are 4 different ways of detaching switches from relay. I can only count three ways at that section:

- SetOption114
- Rules
- SwitchTopic

What is the fourth way?

**Comment by JeffersonRyan** [comment]
"Detach Switches Based On.." seems to me a very odd way to start that section. I could not understand the thought flow after reading the first words of the following paragraph, assumed it was unrelated and fixated on that dangling "To detach switches". If I knew that was only meant to be a link to the last section I probably would take the time to read more carefully. 

Moreover, I'm still not used to things like "When SetOption114 1 all ". My brain misses the "=" or ":" symbol. I know this is not "wrong". I'm just not used to it. And when I started to read the docs two months ago it was definitely confusing.  

I would write that section as:

### Detaching switches from relays  

There are currently three (four?) ways to do that:

- SetOption114
- Rules
- SwitchTopic
- ?

 ----follow with the explanation of each option

**Comment by barbudor** [comment]
Thanks for your feedback.
Indeed only 3 (three) ways, I counted too fast. 

As you seem very enthusiastic about getting this right, may I suggest that you hit the pencil icon on the top of the page to submit a doc update?

Regarding commands, the best option is to surround then with backticks so they appear  like `Setoption114 1` which makes obvious they are a command verb and a parameter.

Thanks for helping us improving Tasmota. All contributions are welcome.
