### ISSUE TITLE
Please document on variables in the Tasmota docs

### ISSUE THREAD

**Issue by GijsTimmers** [tasmota/docs#605]
There must be some variables available in Tasmota. For instance, in wifi config: `%s-%04d`. It seems like these variables are not documented.

**Comment by barbudor** [comment]
All varaibles that you can access in Rules or Scripting-Language are documented.

What you are referring is not a variable but a way that `hostname` is build by default as `%topic%_XXXX` where XXXX are the least 4 digits of the MAC address converted as a decimal number.
Already documented here : [hostname](https://tasmota.github.io/docs/Commands/#hostname)
