### ISSUE TITLE
Leading edge dimmer not working for 4 channel RobotDyn

### ISSUE THREAD

**Issue by AleksandarKotsev** [tasmota/docs#617]
Dear Team,

The description for connection a zero-crossing dimmer doesn't work for connecting a 4 channel RobotDyn dimmer
https://robotdyn.com/ac-light-dimmer-module-4-channel-3-3v-5v-logic-ac-50-60hz-220v-110v.html
I'm using only one channel, but the light only flickers without dimming and I cannot event turn it off.
The described single channel dimmer and the 4 channel one only differ in number of channels and one capacitator.
@stefanbode I need your help. Can you please verify that the recipe isn't missing some ingredients, and it really works for the RobotDyn dimmers.
Best regards,
A.Kotsev

**Comment by AleksandarKotsev** [comment]
@stefanbode, I figured out how to make the dimmer working. It generally works fine, but has some issued running at full brightness and 0 (and close to zero) value of the pwm. After going through the code I also noticed that only one PWM is supported. I want to help you modify the code to work wit all the available PWMs (5). If you are interested in collaboration please leave a contact.
Best regards,
A.Kotsev

**Comment by stefanbode** [comment]
You can reach me on Skype Stefan.bode or via email at Stefan_Bode at web dot de. We can talk about dimming and why 1% is far from easy. But anyhow all input is welcome.
