### ISSUE TITLE
Please add the new feature to documentation

### ISSUE THREAD

**Issue by sensor-freak** [tasmota/docs#623]
@
re PR: arendst/tasmota#

Please add another recovery method to page [Device Recovery](https://github.com/tasmota/docs/Device-Recovery.md)

Another option to perform device recovery (at least for ESP32 devices) is to erase the flash using the esptool:
```
esptool.exe --chip esp32 --port com4 erase_flash
```
This might be helpful if the other options don't work at all. (I had a device which couldn't start sucessfully, probably because of invalid data in the file system. By erasing the complete flash I was able to recover from this situation.)

Kind regards

**Comment by barbudor** [comment]
Erasing and reflashing is already/now documented here: [That Didn't Work, What Now?](https://tasmota.github.io/docs/Device-Recovery/#that-didnt-work-what-now)
