### ISSUE TITLE
Images missing in EXS relay documentation?

### ISSUE THREAD

**Issue by digitaltrousers** [tasmota/docs#685]
@blakadder 
re PR: arendst/tasmota#
Please add the new feature to the appropriate article in [Tasmota documentation](https://github.com/tasmota/docs)
In the 'Notes' section of docs/devices/EXS-Relay-V3.1-&-V5.1.md there appears to be reference to some images which are absent?
https://github.com/tasmota/docs/blob/3440f6d8ec6d17d44fbaad0d16bdda3df0c84cdd/docs/devices/EXS-Relay-V3.1-&-V5.1.md
Thanks.

**Comment by blakadder** [comment]
no clue what images are supposed to be referenced, the code did not have any changes
