### ISSUE TITLE
[Pinout]: Wrong diagram for TYWE3L

### ISSUE THREAD

**Issue by GumbyMan82** [tasmota/docs#761]
It seems that the pinouts in the docs are mirrored compared to the official docs from the chip
The official doc (taken from https://fccid.io/2ANDL-TYWE3L/User-Manual/User-Manual-3894982) shows:
![image](https://user-images.githubusercontent.com/40233411/123005748-ebe39000-d3b6-11eb-97c5-e59e07e3fa7e.png)

I've realized it after almost burning my finger when touching the USB/TTL converter...

**Comment by blakadder** [comment]
Funnily enough the original image was also taken from the official doc ;)
