### ISSUE TITLE
Conflicting instruction on placing EZO module into i2c mode

### ISSUE THREAD

**Issue by maniscalcojohn** [tasmota/docs#777]
@
re PR: arendst/tasmota#

Please add the new feature to the appropriate article in [Tasmota documentation](https://github.com/tasmota/docs)

The instructions to place the EZO into i2c mode for use with Tasmota instruct the user to short the TX and PGND pins, but the diagram says to short the TX and PRB pins.

https://tasmota.github.io/docs/EZO/

**Comment by blakadder** [comment]
@tichris0 can you clarify which is true?

**Comment by tichris0** [comment]
Hmm  He's correct.  The diagram is wrong.  The wording is accurate.  You want to short TX & PGND.

**Comment by blakadder** [comment]
fixed
