### ISSUE TITLE
Dead link in documentation of ESP32 (docs/docs/ESP32.md)

### ISSUE THREAD

**Issue by SHA-NDY** [tasmota/docs#789]
The link to the required flash files for ESP32 in docs/docs/ESP32.md is dead. It points to [https://github.com/arendst/Tasmota/tree/firmware/release-firmware/tasmota32/ESP32_needed_files](https://github.com/arendst/Tasmota/tree/firmware/release-firmware/tasmota32/ESP32_needed_files) and I don't know wheter it moved or became obsolete.

Thanks

**Comment by blakadder** [comment]
fixed.. https://github.com/arendst/Tasmota-firmware/tree/main/release-firmware/tasmota32/ESP32_needed_files
