### ISSUE TITLE
add docs for I2C HT16K33 based 7 segment LED

### ISSUE THREAD

**Issue by HarHarLinks** [tasmota/docs#902]
@tthk
PRs like arendst/tasmota#8116, arendst/tasmota#8900 seem to not have made it to the docs properly.

For a list of things I couldn't find in the docs, see https://github.com/arendst/Tasmota/discussions/14451

Please add the new feature to the appropriate article in [Tasmota documentation](https://github.com/tasmota/docs)

**Comment by ascillato** [comment]
Hi,

This issue is duplicated from https://github.com/tasmota/docs/issues/257

Moving your comment to the original issue.

This request to @tthk has already been done. Please, @HarHarLinks help us to add this to the documentation. Thanks a lot!
