### ISSUE TITLE
Is SwitchTopic obsolete and need to be removed?

### ISSUE THREAD

**Issue by Prologer** [tasmota/docs#951]
I connected a sensor to a GPIO as switch. I tried "SwitchTopic 1" and got Command Unknown as Result.

**Comment by barbudor** [comment]
Still alive and kicking 😂
```
21:22:52.343 CMD: SwitchTopic 1
21:22:52.350 MQT: stat/nodemcu/SWITCHTOPIC = {"SwitchTopic":"nodemcu"}
```
Please open a discusssion on Tasmota https://github.com/arendst/Tasmota/discussions
Or join the Discord server
