### ISSUE TITLE
MQTT rc-2

### ISSUE THREAD

**Issue by Tom618s** [tasmota/docs#970]
![Screenshot_2022-04-15-22-10-59-246_com android chrome](https://user-images.githubusercontent.com/95147431/163656054-538bc38f-376e-437a-9049-19667c92adaa.jpg)
Esse problema é a partir da versão 9.3.0
Se baixar a versão 9.1.0 esse problema ainda não existia 
Para quem está tendo esse problema basta baixar a versão mais antiga

**Comment by barbudor** [comment]
Please use English
This is the DOC repository. 
For any help in using Tasmota software please open a discussion on https://github.com/arendst/Tasmota/discussions
