### ISSUE TITLE
Please add the new feature to documentation

### ISSUE THREAD

**Issue by ichbaum** [tasmota/docs#976]
@
re PR: arendst/tasmota#

Please add the new feature to the appropriate article in [Tasmota documentation](https://tasmota.github.io/docs/Smart-Meter-Interface/#)

KAIFA MB310H4BDE

>D
>B
=>sensor53 r
>M 1
+1,3,s,0,9600,Haus  
1,77070100010800ff@1000,Zaehlerstand In,KWh,Total_in,2
1,77070100020800ff@1000,Zaehlerstand Out,KWh,Total_out,2
1,77070100100700ff@1,Leistung-akt.,W,Power_curr,0
1,77070100600100ff@#,Server-ID,,Meter_Number,0
#

**Comment by barbudor** [comment]
@ichbaum You can add this yourself by hitting the pencil button on right top of the documentation and submitting a PR
