### ISSUE TITLE
IF statement preceded by other Tasmota command - different behaviour from docs

### ISSUE THREAD

**Issue by shanejohnpaul** [tasmota/docs#978]
In https://tasmota.github.io/docs/Rules/#conditional-rules it says

> When the if-statement is preceded by other Tasmota commands you should use Backlog rather than Do , e.g.
`Rule1 ON ENERGY#Current>10 Backlog Power1 0; IF (%var1%==1) Power1 1 ENDIF;Power 2 0;Power3 1 ENDON `
and not
 `Rule1 ON ENERGY#Current>10 DO Power1 0; IF (%var1%==1) Power1 1 ENDIF ENDON`

But for me only the following worked,
`Rule1 ON Switch1#State=2 DO Backlog Power1 OFF; IF (var1==2) ruletimer1 5 ENDIF ENDON`

and the below command did not work
`Rule1 ON Switch1#State=2 Backlog Power1 OFF; IF (var1==2) ruletimer1 5 ENDIF ENDON`

**Comment by barbudor** [comment]
You are correct.
The way the code is build, a proper rule must start with `ON`, have a `DO` and end with either `ENDON` or `BREAK`
`Backlog` cannot replace the `DO`
I remember this have been discussed some time ago but apprently we forgot to update the docs

Can you provide a PR on the docs ?

**Comment by shanejohnpaul** [comment]
Alright, I'll make one.
