### ISSUE TITLE
Command BlinkCount limits are wrong in docs

### ISSUE THREAD

**Issue by Snapstromegon** [tasmota/docs#993]
@
re PR: arendst/tasmota#

Please correct the BlinkCount limits in the [Tasmota documentation](https://github.com/tasmota/docs) commands section.

It currently states, that the value for `BlinkCount` is limited to **0..32000**, but it's actually valid to use the full uint16 range up to **65535**.

Either this should be enforced in code, or the docs should be updated to reflect the correct ranges.

I'm currently writing a Tasmota RPC interface and might come across more of these cases. What is the preferred way of bringing those up (Single Issue, seperate issues, single PR, seperate PRs)?

**Comment by Snapstromegon** [comment]
Woudln't it be better to allow up to `2^15-1` (32767)?
This would allow the maximum value to be usable.

**Comment by arendst** [comment]
I know but for "normal" users that's a strange number. 32000 is more rememberable ;-)

**Comment by Snapstromegon** [comment]
Then you could also argument for a round 30000 since thats even more rememberable (and be a round 50 minutes).
To me this feels like an arbitrary hard limitation that doesn't have a technical reason.

I don't know what the ideal solution would be here, but I definetly would limit it by code at the point of technical reasoning (32767). Wether or not the docs will accurately reflect that is for me up to debate.
