### ISSUE TITLE
Can't connect to Azure IoT Hub

### ISSUE THREAD

**Issue by Padu98** [tasmota/docs#998]
Hi, 
I recently followed this totorial: https://tasmota.github.io/docs/Azure-IoT-Hub/ connection an azure iot device to my tasmota device.
After following the steps I get the following error message in the tasmota console: 

Attempting connection...
MQT: Authenticating with an Azure IoT Hub Token
MQT: TLS connection error: 0
Connect failed to ****.azure-devices.net:8883, rc -2. Retry in 110 sec

I know those logs do no provide much information but is there still anybody who can help?

In the MQTT configuration I used the following inputs:
1: iothubname.azure-devices.net
2: 8883
3: deviceId
4: deviceId
5: deviceId primaty Key (should I use an IoT-Hub primary key instead?)
6: tasmota
7: tasmota

And yes I did put the following in my user_config_override.h file before flashing the device:

#ifndef USE_MQTT_TLS
#define USE_MQTT_TLS
#endif
#define USE_MQTT_AZURE_IOT

Thanks in advance!

**Comment by arendst** [comment]
Wrong location for reporting. Try this https://github.com/arendst/Tasmota/issues/15809
